### ISSUE TITLE
部署的详细步骤

### ISSUE THREAD

**Issue by anson2416** [jiajunhuang/tgbot#4]
请问你有详细的部署步骤吗？例如sql数据库的建表，库的依赖等。谢谢指导。

**Comment by jiajunhuang** [comment]
> 请问你有详细的部署步骤吗？例如sql数据库的建表，库的依赖等。谢谢指导。

基本上就是README里写的那样，执行 `python main.py` 就会启动bot，`python web.py` 就会启动web服务器。另外你的头像。。。
